# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1787d985023026ab809e710464bcd3ce0a975b85891456e622360bc2e8858a01108fd4da7a2b2c2fcf6cadc8beffca2d2db718a5e0a234cdc7cc76e1fcc090c1

test:
  secret_key_base: 0e5a6c55fb01a957748fc3118e3a01a3bd0f2f66f184f829fb8ecf0d281c73c55991bc8f80f9e2d044e787fd5f8938f74b3c27bc90f0399ef52052da08fe9b47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
